name: dartvectormath
description: A Vector Math library for game programming written in Dart.
version: 0.8.5
authors: 
- John McCutchan <john@johnmccutchan.com>
- Adam Singer <financeCoding@gmail.com>
homepage: https://johnmccutchan.github.com/DartVectorMath
dependencies:
  unittest:
    sdk: unittest
