name: vector_math
version: 1.3.2
author: John McCutchan <john@johnmccutchan.com>
description: A Vector Math library for 2D and 3D applications.
homepage: https://github.com/johnmccutchan/vector_math
dev_dependencies:
  unittest: any
  browser: any
  hop: any
